./gen.sh \
    --tls_maybe y \
    --rbac_maybe n \
    --root_certificate_maybe y \
    --root_certificate_name root \
    --specify_details_maybe n \
    --openssl_cnf_maybe n \
    --password citrusstore \
    --key_pair_maybe y \
    --key_password citrusstore \
    --mutual_auth_maybe n \
    --client_name brawn \
    --server_name brawn \
    --port 5000 \
    --host 127.0.0.1
