name: Reusable Steps

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py
        pip install -r requirements.txt
      working-directory: tests

    - name: Retrieve the secret and decode it to a file
      env:
        FEATURE_FILE: ${{ secrets.FEATURE_FILE }}
      run: |
        echo $FEATURE_FILE | base64 --decode > features.conf 
      working-directory: tests

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: aerospike.jfrog.io
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_PASSWORD }}